import type { Memory } from '../../types';
import travelPhoto from '../../assets/login/travel-photo.png';

/**
 * 落地页只读 Demo 记忆源。
 *
 * 设计约束（与真实产品共用同一套 UI 组件，仅替换数据源）：
 * 1. 固定年份 / 固定坐标 / 固定文案，全部只读，不接受任何写入。
 * 2. 行政字段（country/province/city/district/adcode）与经纬度全部补齐，
 *    使 MapView 的地址补全逻辑判定为「已解析」，从而不发起任何地理编码网络请求。
 * 3. 图片使用仓库内本地资源，不依赖远端图床，公开落地页零生产数据暴露。
 */
export const DEMO_MEMORIES: Memory[] = [
  {
    id: 'demo-2007',
    title: '胡同口的老槐树与单车',
    date: '2007-10-01',
    year: 2007,
    category: 'growth',
    tag: '时空足迹地图',
    image: travelPhoto,
    gallery: [],
    pastSelf: '那年秋天风吹过什刹海的水面，银锭桥边的冰糖葫芦冒着热气。',
    presentSelf: '第一次意识到，原来很多地方都值得被认真记住。',
    pinnedBy: 'pin',
    px: 20,
    py: 30,
    rotation: -1,
    country: '中国',
    province: '北京市',
    city: '北京市',
    district: '西城区',
    adcode: '110102',
    locationProvider: 'amap',
    location: { name: '什刹海', mx: 30, my: 40 },
    lat: 39.9355,
    lng: 116.3885,
  },
  {
    id: 'demo-2012',
    title: '大昭寺金顶的日暮日光',
    date: '2012-05-15',
    year: 2012,
    category: 'travel',
    tag: '实体旅行手账',
    image: travelPhoto,
    gallery: [],
    pastSelf: '空气稀薄而通透，酥油茶的香气在转经道上久久不散。',
    presentSelf: '多年后再看这张照片，仍能想起金顶被夕阳点燃的那一刻。',
    pinnedBy: 'tape',
    px: 38,
    py: 50,
    rotation: 0,
    country: '中国',
    province: '西藏自治区',
    city: '拉萨市',
    district: '城关区',
    adcode: '540102',
    locationProvider: 'amap',
    location: { name: '八廓街', mx: 44, my: 55 },
    lat: 29.6528,
    lng: 91.1321,
  },
  {
    id: 'demo-2018',
    title: '初夏傍晚的微风与蝉鸣',
    date: '2018-07-21',
    year: 2018,
    category: 'photography',
    tag: '端到端离线加密',
    image: travelPhoto,
    gallery: [],
    pastSelf: '坐在河畔石阶上看着远处群山隐没在蓝紫色的暮色中。',
    presentSelf: '安静下来的时候，风景才真正开始说话。',
    pinnedBy: 'magnet',
    px: 56,
    py: 30,
    rotation: 1,
    country: '日本',
    province: '京都府',
    city: '京都市',
    district: '东山区',
    locationProvider: 'bigdatacloud',
    location: { name: '鸭川河畔', mx: 60, my: 42 },
    lat: 35.0116,
    lng: 135.7681,
  },
  {
    id: 'demo-2022',
    title: '深秋松针上的初雪',
    date: '2022-10-04',
    year: 2022,
    category: 'travel',
    tag: '胶片级分档画廊',
    image: travelPhoto,
    gallery: [],
    pastSelf: '松石绿色的水蜿蜒在晨雾里，木栈道上落满了金黄的落叶。',
    presentSelf: '有些冷冽的清晨，是记忆里最清晰的高光。',
    pinnedBy: 'clip',
    px: 74,
    py: 50,
    rotation: -1,
    country: '中国',
    province: '新疆维吾尔自治区',
    city: '阿勒泰地区',
    district: '布尔津县',
    adcode: '654321',
    locationProvider: 'amap',
    location: { name: '喀纳斯月亮湾', mx: 78, my: 58 },
    lat: 48.7443,
    lng: 87.0296,
  },
  {
    id: 'demo-2026',
    title: '阳光穿过法桐叶的微光',
    date: '2026-05-18',
    year: 2026,
    category: 'motorcycle',
    tag: 'Web & Mobile 协同',
    image: travelPhoto,
    gallery: [],
    pastSelf: '重新整理过去所有的旅程与笔记，将每一处时光装进所忆。',
    presentSelf: '把散落的日子收拢成一条可以回望的轨迹。',
    pinnedBy: 'pin',
    px: 92,
    py: 30,
    rotation: 0,
    country: '中国',
    province: '上海市',
    city: '上海市',
    district: '徐汇区',
    adcode: '310104',
    locationProvider: 'amap',
    location: { name: '武康庭', mx: 92, my: 40 },
    lat: 31.209,
    lng: 121.443,
  },
];

export default DEMO_MEMORIES;
